In [1]:
!cat t_sne.py | pbcopy


In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.manifold import TSNE
import load_data

def main(labels):
    img_list=[]
    label_list=[]
    true_list=[]
    for dec in labels:
        img_list.append(dec['image'])
        label_list.append(dec['label'])
        true_list.appens(dec['true_label'])
    X_reduced = TSNE(n_components=2, random_state=0).fit_transform(img_list)
    plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=label_list)
    plt.colorbar()
    
if __name__ == '__main__':
    testloader, train_labels_error, trainloader, label_zero, label_one, label_two, label_three, label_four, label_five, label_six, label_seven, label_eight, label_nine = load_data.get_img()


/Users/karenkosaka/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torchvision-0.2.3a0+ccbb322-py3.6.egg/torchvision/datasets/mnist.py:43: UserWarning: train_labels has been renamed targets


TypeError: eq() received an invalid combination of arguments - got (str), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (str)
 * (Number other)
      didn't match because some of the arguments have invalid types: (str)


In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.manifold import TSNE
import load_data

def main(labels):
    img_list=[]
    label_list=[]
    true_list=[]
    for dec in labels:
        img_list.append(dec['image'])
        label_list.append(dec['label'])
        true_list.appens(dec['true_label'])
    X_reduced = TSNE(n_components=2, random_state=0).fit_transform(img_list)
    plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=label_list)
    plt.colorbar()
    
if __name__ == '__main__':
    testloader, train_labels_error, trainloader, label_zero, label_one, label_two, label_three, label_four, label_five, label_six, label_seven, label_eight, label_nine = load_data.get_img()
    

/Users/karenkosaka/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torchvision-0.2.3a0+ccbb322-py3.6.egg/torchvision/datasets/mnist.py:43: UserWarning: train_labels has been renamed targets
/Users/karenkosaka/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torchvision-0.2.3a0+ccbb322-py3.6.egg/torchvision/datasets/mnist.py:53: UserWarning: train_data has been renamed data


tensor([5, 0, 4,  ..., 5, 0, 8])
60000
11960
19.933333333333334


In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.manifold import TSNE
import load_data

def main(labels):
    img_list=[]
    label_list=[]
    true_list=[]
    for dec in labels:
        img_list.append(dec['image'])
        label_list.append(dec['label'])
        true_list.append(dec['true_label'])
    X_reduced = TSNE(n_components=2, random_state=0).fit_transform(img_list)
    plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=label_list)
    plt.colorbar()
    
if __name__ == '__main__':
    testloader, train_labels_error, trainloader, label_zero, label_one, label_two, label_three, label_four, label_five, label_six, label_seven, label_eight, label_nine = load_data.get_img()
    main(label_zero)


tensor([5, 0, 4,  ..., 5, 6, 8])
60000
12050
20.083333333333332


ValueError: only one element tensors can be converted to Python scalars

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.manifold import TSNE
import load_data

def main(labels):
    img_list=[]
    label_list=[]
    true_list=[]
    for dec in labels:
        img_list.append(dec['image'].numpy())
        label_list.append(dec['label'])
        true_list.append(dec['true_label'])
    
    X_reduced = TSNE(n_components=2, random_state=0).fit_transform(img_list)
    plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=label_list)
    plt.colorbar()
    
if __name__ == '__main__':
    testloader, train_labels_error, trainloader, label_zero, label_one, label_two, label_three, label_four, label_five, label_six, label_seven, label_eight, label_nine = load_data.get_img()
    main(label_zero)


/Users/karenkosaka/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torchvision-0.2.3a0+ccbb322-py3.6.egg/torchvision/datasets/mnist.py:43: UserWarning: train_labels has been renamed targets
/Users/karenkosaka/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torchvision-0.2.3a0+ccbb322-py3.6.egg/torchvision/datasets/mnist.py:53: UserWarning: train_data has been renamed data


tensor([7, 0, 7,  ..., 5, 6, 8])
60000
11909
19.848333333333336
